### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by perryraskin** [makinacorpus/spynner#100]
in /private/var/folders/np/qzcg7kvj5y70yj987kp9ptxw0000gn/T/pip-build-6z40obip/autopy/

**Comment by huguesfontenelle** [comment]
```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fg/xdc7m78531jcz2cd3pk4pvlw0000gn/T/pip-build-ppj6lllp/autopy/setup.py", line 50
        print 'Updating __init__.py'
                                   ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'Updating __init__.py')?
```

**Comment by haroldrandom** [comment]
I got the same problem.

Anyone sovled?

**Comment by XCanG** [comment]
autopy (https://github.com/msanders/autopy) probably writed under python2 and same with spynner
