### ISSUE TITLE
Fail setup in python 3.4

### ISSUE THREAD

**Issue by cuongdn** [makinacorpus/spynner#66]
I try to install spynner under python 3.4 but I am getting these errors (it works when installing under  python 2.7.8). Here's the error log. Any idea to fix this?

C:\Users\Admin\Downloads\Compressed\spynner-2.19>python setup.py install
running install
running bdist_egg
running egg_info
writing dependency_links to src\spynner.egg-info\dependency_links.txt
writing top-level names to src\spynner.egg-info\top_level.txt
writing src\spynner.egg-info\PKG-INFO
writing requirements to src\spynner.egg-info\requires.txt
reading manifest file 'src\spynner.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.txt'
warning: no files found matching '*' under directory 'docs'
warning: no previously-included files matching '*pyc' found anywhere in distribu
tion
warning: no previously-included files matching '.*.cfg' found anywhere in distri
bution
writing manifest file 'src\spynner.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\spynner
copying build\lib\spynner\browser.py -> build\bdist.win-amd64\egg\spynner
creating build\bdist.win-amd64\egg\spynner\javascript
copying build\lib\spynner\javascript\jquery-1.5.2.js -> build\bdist.win-amd64\eg
g\spynner\javascript
copying build\lib\spynner\javascript\jquery.min.js -> build\bdist.win-amd64\egg\
spynner\javascript
copying build\lib\spynner\javascript\jquery.simulate.js -> build\bdist.win-amd64
\egg\spynner\javascript
copying build\lib\spynner\javascript\test.html -> build\bdist.win-amd64\egg\spyn
ner\javascript
copying build\lib\spynner\javascript\__init__.py -> build\bdist.win-amd64\egg\sp
ynner\javascript
creating build\bdist.win-amd64\egg\spynner\tests
copying build\lib\spynner\tests\html_controls.html -> build\bdist.win-amd64\egg\
spynner\tests
copying build\lib\spynner\tests\spynner.rst -> build\bdist.win-amd64\egg\spynner
\tests
copying build\lib\spynner\tests\t.html -> build\bdist.win-amd64\egg\spynner\test
s
copying build\lib\spynner\tests\__init__.py -> build\bdist.win-amd64\egg\spynner
\tests
copying build\lib\spynner\__init__.py -> build\bdist.win-amd64\egg\spynner
byte-compiling build\bdist.win-amd64\egg\spynner\browser.py to browser.cpython-3
4.pyc
byte-compiling build\bdist.win-amd64\egg\spynner\javascript\__init__.py to __ini
t__.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\spynner\tests\__init__.py to __init__.c
python-34.pyc
byte-compiling build\bdist.win-amd64\egg\spynner\__init__.py to __init__.cpython
-34.pyc
installing package data to build\bdist.win-amd64\egg
running install_data
creating build\bdist.win-amd64\egg\share
creating build\bdist.win-amd64\egg\share\doc
creating build\bdist.win-amd64\egg\share\doc\spynner
creating build\bdist.win-amd64\egg\share\doc\spynner\examples
copying examples\anothergoogle.py -> build\bdist.win-amd64\egg\share\doc\spynner
\examples
creating build\bdist.win-amd64\egg\EGG-INFO
copying src\spynner.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying src\spynner.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying src\spynner.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\E
GG-INFO
copying src\spynner.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying src\spynner.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO

zip_safe flag not set; analyzing archive contents...
creating 'dist\spynner-2.19-py3.4.egg' and adding 'build\bdist.win-amd64\egg' to
 it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing spynner-2.19-py3.4.egg
Removing c:\program files\python\lib\site-packages\spynner-2.19-py3.4.egg
Copying spynner-2.19-py3.4.egg to c:\program files\python\lib\site-packages
spynner 2.19 is already the active version in easy-install.pth

Installed c:\program files\python\lib\site-packages\spynner-2.19-py3.4.egg
Processing dependencies for spynner==2.19
Searching for autopy
Reading https://pypi.python.org/simple/autopy/
Best match: autopy 0.51
Downloading https://pypi.python.org/packages/source/a/autopy/autopy-0.51.tar.gz#
md5=b92055aa2a3712a9c3b4c874014b450e
Processing autopy-0.51.tar.gz
Writing C:\Users\Admin\AppData\Local\Temp\easy_install-p020ks2l\autopy-0.51\setu
p.cfg
Running autopy-0.51\setup.py -q bdist_egg --dist-dir C:\Users\Admin\AppData\Loca
l\Temp\easy_install-p020ks2l\autopy-0.51\egg-dist-tmp-pwwc7rux
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    'Topic :: Internet :: WWW/HTTP',
  File "C:\Program Files\Python\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\Python\lib\distutils\dist.py", line 955, in run_command
s
    self.run_command(cmd)
  File "C:\Program Files\Python\lib\distutils\dist.py", line 974, in run_command

    cmd_obj.run()
  File "C:\Program Files\Python\lib\site-packages\setuptools\command\install.py"
, line 74, in run
    self.do_egg_install()
  File "C:\Program Files\Python\lib\site-packages\setuptools\command\install.py"
, line 97, in do_egg_install
    cmd.run()
  File "C:\Program Files\Python\lib\site-packages\setuptools\command\easy_instal
l.py", line 358, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Program Files\Python\lib\site-packages\setuptools\command\easy_instal
l.py", line 574, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Program Files\Python\lib\site-packages\setuptools\command\easy_instal
l.py", line 625, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Program Files\Python\lib\site-packages\setuptools\command\easy_instal
l.py", line 671, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "C:\Program Files\Python\lib\site-packages\pkg_resources.py", line 564, i
n resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "C:\Program Files\Python\lib\site-packages\pkg_resources.py", line 802, i
n best_match
    return self.obtain(req, installer) # try and download/install
  File "C:\Program Files\Python\lib\site-packages\pkg_resources.py", line 814, i
n obtain
    return installer(requirement)
  File "C:\Program Files\Python\lib\site-packages\setuptools\command\easy_instal
l.py", line 593, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Program Files\Python\lib\site-packages\setuptools\command\easy_instal
l.py", line 623, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Program Files\Python\lib\site-packages\setuptools\command\easy_instal
l.py", line 809, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Program Files\Python\lib\site-packages\setuptools\command\easy_instal
l.py", line 1015, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Program Files\Python\lib\site-packages\setuptools\command\easy_instal
l.py", line 1000, in run_setup
    run_setup(setup_script, args)
  File "C:\Program Files\Python\lib\site-packages\setuptools\sandbox.py", line 5
0, in run_setup
    lambda: execfile(
  File "C:\Program Files\Python\lib\site-packages\setuptools\sandbox.py", line 1
00, in run
    return func()
  File "C:\Program Files\Python\lib\site-packages\setuptools\sandbox.py", line 5
2, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "C:\Program Files\Python\lib\site-packages\setuptools\compat.py", line 78
, in execfile
    exec(compile(source, fn, 'exec'), globs, locs)
  File "setup.py", line 50
    print 'Updating __init__.py'
                               ^
SyntaxError: invalid syntax

**Comment by mattmarnell** [comment]
I'm seeing a similar error:

Writing C:\Users\USER~1\AppData\Local\Temp\easy_install-s4_a8vu4\autopy-0.51\s
etup.cfg
Running autopy-0.51\setup.py -q bdist_egg --dist-dir C:\Users\USER~1\AppData\L
ocal\Temp\easy_install-s4_a8vu4\autopy-0.51\egg-dist-tmp-26pvnmy0
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    'Topic :: Internet :: WWW/HTTP',
  File "C:\Python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 74, i
n run
    self.do_egg_install()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 97, i
n do_egg_install
    cmd.run()
  File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line
358, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line
574, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line
625, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line
671, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 564, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 802, in best_match

    return self.obtain(req, installer) # try and download/install
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 814, in obtain
    return installer(requirement)
  File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line
593, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line
623, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line
809, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line
1015, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line
1000, in run_setup
    run_setup(setup_script, args)
  File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 50, in run_se
tup
    lambda: execfile(
  File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 100, in run
    return func()
  File "C:\Python34\lib\site-packages\setuptools\sandbox.py", line 52, in <lambd
a>
    {'__file__':setup_script, '__name__':'__main__'}
  File "C:\Python34\lib\site-packages\setuptools\compat.py", line 78, in execfil
e
    exec(compile(source, fn, 'exec'), globs, locs)
  File "setup.py", line 50
    print 'Updating __init__.py'
                               ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by yangl1996** [comment]
encountered exactly the similar issue.

**Comment by kiorky** [comment]
dup of #65
