### ISSUE TITLE
spynner ImportError: No module named urllib

### ISSUE THREAD

**Issue by const669** [makinacorpus/spynner#73]
Hello!
I get ImportError when using spynner, but in other script this error does not appear. In other script I use urllib too.

> python parsing.py
Traceback (most recent call last):
  File "parsing.py", line 2, in <module>
    import spynner
  File "build/bdist.linux-i686/egg/spynner/__init__.py", line 2, in <module>
  File "build/bdist.linux-i686/egg/spynner/browser.py", line 28, in <module>
ImportError: No module named urllib

**Comment by kiorky** [comment]
envionment problem i think, check your python installation.
